version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  db2:
    postgres:
      container_name: postgre-db
      ports: '10000:3306'
      environment:
        POSTGRES_USER: dbuser
        POSTGRES_PASSWORD: HuDcT0HNy5zQRVEo7Vt6c1566CUnxqEL

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3010 -b '0.0.0.0'"
    volumes:
      - '.:/app'
    ports:
      - "3010:3010"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_HOST: db
volumes:
  mysql-data:
    driver: local

